"""
rotate_images.py

Script to rotate images, useful for checking if an images generated by 
image_generator.py is accurate to the TLE and observer information given. 

To check if images match, use image_rotator to rotate the image until it aligns with 
the orientation of the real image that you are comparing it to.

"""

#---inputs---
import argparse
from PIL import Image
#------------

def main(sim_image, ang, real_image):
    """Main function
    inputs: 
    - the simulated image
    - the real image
    - the angle to rotate the simulated image (degrees)
    Results: 
    - plots the rotated simulated image next to the real one
    """

    img = Image.open(sim_image)
    rot = img.rotate(ang, expand = True)

    rot.show()

    if real_image != None:
        r_img = Image.open(real_image)
        r_img.show()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='''This script will rotate a simulated png and then display it, for comparasin against 
                                     a real image.''')
    parser.add_argument('sim_image', type = str, help = 'simulated image file')
    parser.add_argument('ang', type = float, help = 'rotation angle')
    parser.add_argument('-ri', '--real_image', type = str, help = 'real image for comparasin', default = None)

    args = parser.parse_args()
    
    main(args.sim_image, args.ang, args.real_image)